# Generated by Django 4.1.6 on 2023-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vps', models.CharField(max_length=10)),
                ('cpu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hdd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Precio Recursos VPS',
            },
        ),
    ]
