# Generated by Django 4.1.6 on 2023-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='cpu_limit',
            field=models.IntegerField(default=1, help_text='Cantidad', verbose_name='Limite de CPU'),
        ),
        migrations.AddField(
            model_name='precio',
            name='hdd_limit',
            field=models.IntegerField(default=1, help_text='en GB', verbose_name='Limite de HDD'),
        ),
        migrations.AddField(
            model_name='precio',
            name='ram_limit',
            field=models.IntegerField(default=1, help_text='en GB', verbose_name='Limite de RAM'),
        ),
    ]
